# -*- coding: utf-8 -*-
"""bdl-2023-assignment1-main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OLsqWcjJItBXovss4GBseCI4kuVR2aj6
"""

import os
import flask

def hello_world(request):
         return "Hello World!"

def calculate_fibonacci(n):
 # complete this function
        sum = 1
        prev_1 = 0
        prev_2 = 0
        if n<10 or n>100:
                return "Input must be between 10 and 100"
        temp =1
        for i in range(1,n):
                prev_2 = prev_1
                prev_1 = temp
                sum +=  prev_1+prev_2
                temp = prev_1+prev_2 
        return sum

def return_fibonacci(request):

        request_args = request.args

        if request_args and "n" in request_args:
                n = int(request_args["n"])

        else:
                n = 1

        return f"{calculate_fibonacci(n)}"

